# Generated by Django 5.2.15 on 2026-06-08 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(default='ERP', max_length=80, verbose_name='連線名稱')),
                ('api_base_url', models.URLField(help_text='例：https://erp.example.com/api', verbose_name='API 基礎網址')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('products_endpoint', models.CharField(default='/products', max_length=200, verbose_name='產品同步端點')),
                ('auth_header', models.CharField(default='Authorization', max_length=60, verbose_name='認證 Header 名稱')),
                ('auth_prefix', models.CharField(default='Bearer', max_length=20, verbose_name='認證前綴')),
                ('is_active', models.BooleanField(default=False, verbose_name='啟用')),
                ('auto_sync', models.BooleanField(default=False, verbose_name='自動同步')),
                ('sync_interval_hours', models.PositiveIntegerField(default=24, verbose_name='同步間隔（小時）')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='上次同步')),
                ('last_sync_status', models.CharField(blank=True, max_length=20, verbose_name='上次狀態')),
                ('last_sync_message', models.TextField(blank=True, verbose_name='上次訊息')),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='例：{"name_zh":"item_name","model_no":"item_code","summary_zh":"description"}', verbose_name='欄位對應')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erp_connection', to='showroom.showroomsite')),
            ],
            options={
                'verbose_name': 'ERP 連線',
                'verbose_name_plural': 'ERP 連線',
            },
        ),
        migrations.CreateModel(
            name='ErpSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('status', models.CharField(choices=[('ok', '成功'), ('error', '失敗')], max_length=20, verbose_name='狀態')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='新增')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='更新')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='略過')),
                ('message', models.TextField(blank=True, verbose_name='訊息')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='showroom.erpconnection')),
            ],
            options={
                'verbose_name': 'ERP 同步紀錄',
                'verbose_name_plural': 'ERP 同步紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='公司')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='電話')),
                ('job_title', models.CharField(blank=True, max_length=80, verbose_name='職稱')),
                ('country', models.CharField(blank=True, default='Taiwan', max_length=60, verbose_name='國家/地區')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已驗證')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最後登入 IP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '展間會員',
                'verbose_name_plural': '展間會員',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('event_type', models.CharField(choices=[('page_view', '頁面瀏覽'), ('product_view', '產品瀏覽'), ('zone_view', '分區瀏覽'), ('inquiry', '諮詢送出'), ('share', '分享'), ('ar_click', 'AR 點擊'), ('login', '會員登入')], max_length=20, verbose_name='事件類型')),
                ('path', models.CharField(blank=True, max_length=300, verbose_name='路徑')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('referer', models.CharField(blank=True, max_length=300, verbose_name='來源')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='附加資料')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showroom.product')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='showroom.showroomsite')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='showroom.zone')),
            ],
            options={
                'verbose_name': '分析事件',
                'verbose_name_plural': '分析事件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='showroom_an_event_t_bd8946_idx'), models.Index(fields=['site', 'created_at'], name='showroom_an_site_id_69f232_idx')],
            },
        ),
    ]
