# Generated by Django 5.2.15 on 2026-06-10 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_erpconnection_erpsynclog_memberprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_translation_key',
            field=models.CharField(blank=True, help_text='供未來 AI 多語系翻譯批次處理的內容識別鍵', max_length=80, verbose_name='AI 翻譯鍵值'),
        ),
        migrations.AddField(
            model_name='product',
            name='angle_cut_default',
            field=models.FloatField(blank=True, default=0.0, verbose_name='預設切角 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='angle_cut_max',
            field=models.FloatField(blank=True, default=0.0, verbose_name='切角上限 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='angle_cut_min',
            field=models.FloatField(blank=True, default=0.0, verbose_name='切角下限 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.JSONField(blank=True, default=list, help_text='例：["#FFD100","#1E4A8C","#FFFFFF","#2D2D2D"]', verbose_name='可切換顏色列表'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_color_hex',
            field=models.CharField(default='#FFD100', help_text='休閒運動風高反差黃色，確保零組件不被場景吃掉', max_length=7, verbose_name='預設零件色'),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter_default',
            field=models.FloatField(blank=True, default=0.0, verbose_name='預設直徑 (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter_max',
            field=models.FloatField(blank=True, default=0.0, verbose_name='直徑微調上限 (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter_min',
            field=models.FloatField(blank=True, default=0.0, verbose_name='直徑微調下限 (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='elevation_angle_default',
            field=models.FloatField(blank=True, default=0.0, verbose_name='預設仰角 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='elevation_angle_max',
            field=models.FloatField(blank=True, default=0.0, verbose_name='仰角上限 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='elevation_angle_min',
            field=models.FloatField(blank=True, default=0.0, verbose_name='仰角下限 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_position_image',
            field=models.ImageField(blank=True, help_text='零組件於車架上的相對位置示意圖', null=True, upload_to='products/frame/', verbose_name='車架相對定位圖'),
        ),
        migrations.AddField(
            model_name='product',
            name='gltf_file',
            field=models.FileField(blank=True, help_text='Web 端 Three.js 載入用 GLB 檔案', null=True, upload_to='products/gltf/', verbose_name='GLTF/GLB 模型檔'),
        ),
        migrations.AddField(
            model_name='product',
            name='igs_file',
            field=models.FileField(blank=True, help_text='工程原始 CAD 檔（IGS 格式）', null=True, upload_to='products/igs/', verbose_name='IGS 原始檔'),
        ),
        migrations.AddField(
            model_name='product',
            name='joint_angle_default',
            field=models.FloatField(blank=True, default=0.0, verbose_name='預設結合角度 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='joint_angle_max',
            field=models.FloatField(blank=True, default=0.0, verbose_name='結合角度上限 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='joint_angle_min',
            field=models.FloatField(blank=True, default=0.0, verbose_name='結合角度下限 (°)'),
        ),
        migrations.AddField(
            model_name='product',
            name='scale_default',
            field=models.FloatField(default=1.0, verbose_name='預設縮放'),
        ),
        migrations.AddField(
            model_name='product',
            name='scale_max',
            field=models.FloatField(default=1.2, verbose_name='縮放上限'),
        ),
        migrations.AddField(
            model_name='product',
            name='scale_min',
            field=models.FloatField(default=0.8, verbose_name='縮放下限'),
        ),
        migrations.AddField(
            model_name='product',
            name='training_notes_en',
            field=models.TextField(blank=True, verbose_name='教育訓練說明（英文）'),
        ),
        migrations.AddField(
            model_name='product',
            name='training_notes_ja',
            field=models.TextField(blank=True, verbose_name='教育訓練說明（日文）'),
        ),
        migrations.AddField(
            model_name='product',
            name='training_notes_zh',
            field=models.TextField(blank=True, help_text='預留給內部教育訓練與 AI 問答系統的技術說明', verbose_name='教育訓練說明（繁中）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d_url',
            field=models.URLField(blank=True, help_text='GLB/Sketchfab 等備用 CDN 連結', verbose_name='3D 模型外部連結'),
        ),
        migrations.CreateModel(
            name='FactoryPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('plant_type', models.CharField(choices=[('taiwan', '台灣廠（實地取景）'), ('vietnam', '越南廠（數位重構）')], default='taiwan', max_length=20, verbose_name='廠區類型')),
                ('slug', models.SlugField(max_length=80, verbose_name='代碼')),
                ('name_zh', models.CharField(max_length=120, verbose_name='名稱（繁中）')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='名稱（英文）')),
                ('name_ja', models.CharField(blank=True, max_length=120, verbose_name='名稱（日文）')),
                ('description_zh', models.TextField(blank=True, verbose_name='介紹（繁中）')),
                ('description_en', models.TextField(blank=True, verbose_name='介紹（英文）')),
                ('description_ja', models.TextField(blank=True, verbose_name='介紹（日文）')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='封面圖')),
                ('panorama_image', models.ImageField(blank=True, null=True, upload_to='plants/panorama/', verbose_name='360 全景圖')),
                ('panorama_embed_url', models.URLField(blank=True, verbose_name='外部 360 導覽連結')),
                ('asset_gallery', models.JSONField(blank=True, default=list, help_text='越南廠 PPT 截圖、現場照片等路徑列表，供後台上傳管理', verbose_name='廠區資產庫')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('ai_translation_key', models.CharField(blank=True, max_length=80, verbose_name='AI 翻譯鍵值')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='showroom.showroomsite')),
            ],
            options={
                'verbose_name': '廠區',
                'verbose_name_plural': '廠區',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='factory_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='showroom.factoryplant', verbose_name='所屬廠區'),
        ),
        migrations.CreateModel(
            name='ShowroomLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('level_number', models.PositiveSmallIntegerField(default=1, help_text='1=迎賓大廳、2=廠區樞紐、3=製程展區', verbose_name='層級編號')),
                ('level_type', models.CharField(choices=[('lobby', 'Level 1 — 品牌迎賓大廳'), ('factory_hub', 'Level 2 — 雙廠區樞紐'), ('process_deep', 'Level 3 — 深度製程展區')], default='lobby', max_length=20, verbose_name='層級類型')),
                ('slug', models.SlugField(max_length=80, verbose_name='代碼')),
                ('name_zh', models.CharField(max_length=120, verbose_name='名稱（繁中）')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='名稱（英文）')),
                ('name_ja', models.CharField(blank=True, max_length=120, verbose_name='名稱（日文）')),
                ('summary_zh', models.TextField(blank=True, verbose_name='摘要（繁中）')),
                ('summary_en', models.TextField(blank=True, verbose_name='摘要（英文）')),
                ('summary_ja', models.TextField(blank=True, verbose_name='摘要（日文）')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='levels/', verbose_name='封面圖')),
                ('floor_plan_image', models.ImageField(blank=True, help_text='展間平面導覽圖，供導覽列「當前位置」標示', null=True, upload_to='levels/floorplans/', verbose_name='全景地圖')),
                ('panorama_image', models.ImageField(blank=True, null=True, upload_to='levels/panorama/', verbose_name='360 全景圖')),
                ('panorama_embed_url', models.URLField(blank=True, verbose_name='外部 360 導覽連結')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('ai_translation_key', models.CharField(blank=True, help_text='供未來 AI 多語系翻譯系統對應的內容鍵值', max_length=80, verbose_name='AI 翻譯鍵值')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='showroom.showroomsite')),
            ],
            options={
                'verbose_name': '展間層級',
                'verbose_name_plural': '展間層級',
                'ordering': ['sort_order', 'level_number'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='factoryplant',
            name='level',
            field=models.ForeignKey(help_text='通常掛載於 Level 2 廠區樞紐', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='showroom.showroomlevel'),
        ),
        migrations.AddField(
            model_name='product',
            name='showroom_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='showroom.showroomlevel', verbose_name='所屬展間層級'),
        ),
        migrations.AlterUniqueTogether(
            name='factoryplant',
            unique_together={('site', 'slug')},
        ),
    ]
