# Generated by Django 5.2.15 on 2026-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_zone_pipeline_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='step_file',
            field=models.FileField(blank=True, help_text='工程原始 CAD 檔（STEP / STP 格式）', null=True, upload_to='products/step/', verbose_name='STEP 原始檔'),
        ),
        migrations.AlterField(
            model_name='factoryplant',
            name='audio_guide',
            field=models.FileField(blank=True, help_text='廠區環境介紹音檔（MP3/M4A）', null=True, upload_to='plants/audio/', verbose_name='環境語音導覽'),
        ),
        migrations.AlterField(
            model_name='product',
            name='igs_file',
            field=models.FileField(blank=True, help_text='工程原始 CAD 檔（IGS / IGES 格式）', null=True, upload_to='products/igs/', verbose_name='IGS 原始檔'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='audio_guide',
            field=models.FileField(blank=True, help_text='分區解說音檔（MP3/M4A）', null=True, upload_to='zones/audio/', verbose_name='語音導覽'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='photo_gallery',
            field=models.JSONField(blank=True, default=list, help_text='分區現場照片 /media/ 路徑列表，供 AR 導覽瀏覽', verbose_name='現場照片廊'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='pipeline_meta',
            field=models.JSONField(blank=True, default=dict, help_text='AI 強化 pipeline 處理紀錄（stage、preset、processed_at）', verbose_name='Pipeline 狀態'),
        ),
    ]
